### ISSUE TITLE
General Feedback

### ISSUE THREAD

**Issue by cw00dw0rd** [geenen124/imdb_wrangling#1]
This looks good, I only have two comments:
* Regarding your [timestamp note](https://github.com/geenen124/imdb_wrangling/blob/45ffe1bb39eeb67b64cf34d1516b7a152607d2ba/parse_data.py#L84), this timestamp will likely work with the AQL functions so I wouldn't worry about it (but maybe confirm that) 
* What do you think about defining a second edge collection [instead of merging](https://github.com/geenen124/imdb_wrangling/blob/45ffe1bb39eeb67b64cf34d1516b7a152607d2ba/parse_data.py#L124) them into one? The data isn't really related and we can have any number of edge collections in our graph definition. Or would you see keeping these separate as unnecessary complexity?

**Comment by geenen124** [comment]
Thanks for taking a look!

I'll double-check the timestamp functionality once I've uploaded it.

> What do you think about defining a second edge collection instead of merging them into one? The data isn't really related and we can have any number of edge collections in our graph definition. Or would you see keeping these separate as unnecessary complexity?

Good point! I was thinking of splitting out the collections during the initial upload to the DB in a separate python script, and then creating a JSON dump again to make it easier to restore as a one-liner? If you've got a less convoluted way to go about this I'm all ears :)

**Comment by cw00dw0rd** [comment]
That sounds good, restoring the dump is definitely easiest for tutorials.
